#!/bin/bash
if [[ "$1" == "start" ]]; then
  RAILS_ENV=production /opt/puppet-dashboard/script/server -d -e production
  exit 0
fi
if [[ "$1" == "stop" ]]; then
  kill -9 `ps -edf | grep /opt/puppet-dashboard/script/server | grep -v grep | awk '{print $2}'`
  exit 0
fi
