#!/bin/bash
if [[ "$1" == "start" ]]; then
  RAILS_ENV=production /opt/puppet-dashboard/script/delayed_job -p root -n 1 -m $1
  exit 0
fi
if [[ "$1" == "stop" ]]; then
  kill -9 `ps -edf | grep delayed_job | grep -v grep | awk '{print $2}'`
  exit 0
fi
