#!/bin/sh
NAME=mcontrol
PORT=8089
LOG_FILE="/var/log/${NAME}_startup"
LOCATION="/srv/${NAME}"
PID_FILE="/run/${NAME}.pid"

case "$1" in
start)
	echo "Starting ${NAME}..." >> $LOG_FILE
        cd $LOCATION
        bundle install >> $LOG_FILE
        bundle exec rackup -p $PORT -P $PID_FILE -D >> $LOG_FILE
;;
stop)
	echo "Stopping ${NAME}..." >> $LOG_FILE
        if [ -f $PID_FILE ]; then
          kill -9 `cat $PID_FILE` >> $LOG_FILE
        fi
        rm -f $PID_FILE >> $LOG_FILE
        exit 0
;;
status)
        if [ -f $PID_FILE ]; then
          ps -p `cat $PID_FILE` >> $LOG_FILE
          if [ $? -ne 0 ]; then
            echo "Killing stale pid file..." >> $LOG_FILE
            rm -f $PID_FILE >> $LOG_FILE
            echo "Not running"
          else
            echo "Running"
          fi
        else
          echo "Not running"
        fi
;;
esac

